# Use an official Python runtime as a parent image
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

# Set the working directory in the container
ENV NVIDIA_VISIBLE_DEVICES=all


CMD [ "python", "models/GACD_FAS/test.py" ] 
