# Use an official Python runtime as a parent image
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

# Set the working directory in the container
WORKDIR /usr/src/code


CMD [ "python", "models/DGUA_FAS/test.py" ] 
