protocol: "OCI2M"
train_set: ["OULU", "CASIA_MFSD", "Replay_attack"]
test_set: ["MSU_MFSD"]

running_name: ""

PATH:
    data_folder: "./datasets/"
    output_folder: "./logs/"

SYS:
    num_gpus: 1
    GPUs: "0"
    num_workers: 4
MODEL:
    model_name: "resnet18"
    norm: True
    usebias: False
    image_size: 256
    num_classes: 1

TRAIN:
    pretrained: "imagenet"
    batch_size: 96
    lr: 0.005
    fc_lr_scale: 10
    weight_decay: 0.0001
    momentum: 0.9
    lr_step_size: 5
    lr_gamma: 0.5
    optimizer: "SGD"
    scheduler: "step"
    warming_epochs: 1
    epochs: 20

    balance_loader: True
    iter_per_epoch: 10

    rotate: True
    cutout: True
    loss_func: "bce"
    logit_scale: 12
    feat_loss: "supcon"
    lambda_constrast: 0.2

    minimizer: "gac-fas"
    minimizer_warming: 2

    GAC:
        rho: 0.1
        alpha: 0.0002
TEST:
    eval_preq: 5
